version: '3'
services:
  portfolio-dev:
    image: nginx:1.19.2-alpine
    container_name: nginx-dev
    networks:
      - portfolio-server_portfolio
    ports:
      - 3000:80
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
    command: [ nginx-debug, '-g', 'daemon off;' ]

networks:
  portfolio-server_portfolio:
    external: true
