apiVersion: v1
kind: Service
metadata:
  name: portfolio-client-service
  namespace: portfolio
  labels:
    app: portfolio-client
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/app-protocols: '{"http-port":"HTTP"}'
spec:
  type: NodePort
  selector:
    app: portfolio-client
  ports:
    - name: http
      port: 80
      targetPort: 80